---
# tasks file for roles/common
- name: Update apt packages
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - curl
      - vim
      - net-tools
    state: present

