apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - svc.yaml
  - depl.yaml

configMapGenerator:
- name: flaskapp-cm
  literals:
  - MYSQL_DATABASE_USER=root
  - MYSQL_DATABASE_PASSWORD=root
  - MYSQL_DATABASE_DB=BucketList
  - MYSQL_DATABASE_HOST=db-service
