apiVersion: v1
kind: LimitRange
metadata:
  name: testing-limits
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 250m
      memory: 512Mi
    max:
      cpu: 1
      memory: 1Gi
    min:
      cpu: 100m
      memory: 256Mi
    type: Container
