apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker
      imagePullSecrets:
      - name: ecr-access  # Secret manifest created using Terraform
      containers:
      - name: my-app-container
        image: your-image-url   # This gets replaced in CI
        ports:
        - containerPort: 8080
